swagger: "2.0"

info:
  version: 1.0.0
  title: TBD
  description: Spreadsheet ingestor and data management tool for Bureau of Planning and Sustainability's cannabis program.
  contact:
    name: Project Lead
    email: andrew13haley@gmail.com

schemes:
  - http
host: localhost:80
basePath: /

paths:

  /metadata:
    get:
      summary: View file metadata
      description: Displays the contents of the metadata table.
      responses:
        200:
          description: Contents of metadata table
          schema:
            $ref: "#/definitions/Metadata"
        500:
          $ref: "#/responses/Standard500ErrorResponse"

  /list:
    get:
      summary: Displays the contents of a table
      description: Returns a list of the table's records
      parameters:
        - name: table
          in: query
          description: Name of table to display
          type: string
          required: true
      responses:
        200:
          description: Contents of table
        500:
          $ref: "#/responses/Standard500ErrorResponse"

  /load:
    post:
      summary: Uploads a file
      description: Add the contents of a file to the database. The file must be located in the /files directory.
      parameters:
        - name: filename
          in: query
          required: true
          description: Name of file to process
          type: string
      responses:
        200:
          description: File successfully consumed
        400:
          description: File name not supplied
        404:
          description: File could not be located
        500:
          $ref: "#/responses/Standard500ErrorResponse"
    put:
      summary: Inserts a row
      description: Upload a single row and insert it into the named table.
      parameters:
        - name: table
          in: query
          required: true
          description: Name of table to insert into
          type: string
      responses:
        200:
          description: Row insertion successful
        400:
          description: Table name not supplied
        500:
          $ref: "#/responses/Standard500ErrorResponse"

definitions:
  Intake:
    properties:
      row:
        type: integer
      Submission date:
        type: string
        format: date-time
      Entity:
        type: string
      DBA:
        type: string
      Facility Address:
        type: string
      "Facility Suite #":
        type: string
      Facility Zip:
        type: string
      Mailing Address:
        type: string
      MRL:
        type: string
      Neighborhood Association:
        type: string
      Compliance Region:
        type: string
      Primary Contact First Name:
        type: string
      Primary Contact Last Name:
        type: string
      Email:
        type: string
      Phone:
        type: string
      Endorse Type:
        type: string
      License Type:
        type: string
      "Repeat location?":
        type: string
      "App complete?":
        type: string
      Fee Schedule:
        type: string
      Receipt No.:
        type: integer
      Cash Amount:
        type: string
      Check Amount:
        type: string
      Card Amount:
        type: string
      Check No. / Approval Code:
        type: string
      "MRL#":
        type: string
      Notes:
        type: string

  Metadata:
    properties:
      filename:
        type: string
      creator:
        type: string
      size:
        type: integer
        minimum: 0
      created:
        type: string
        format: date-time
      modified:
        type: string
        format: date-time
      lastModifiedBy:
        type: string
      title:
        type: string

  Error:
    properties:
      code:
        type: string
      message:
        type: string

responses:
  Standard500ErrorResponse:
    description: An unexpected error occured.
    schema:
      $ref: "#/definitions/Error"